[package]
authors = ["dnaq"]
description = "Fast cryptographic library for Rust (bindings to libsodium)"
documentation = "https://dnaq.github.io/sodiumoxide"
keywords = ["crypto", "NaCl", "libsodium"]
license = "MIT OR Apache-2.0"
name = "sodiumoxide"
readme = "README.md"
repository = "https://github.com/dnaq/sodiumoxide"
version = "0.0.14"

[dependencies]
libc = "0.2"
libsodium-sys = { path = "libsodium-sys", version = "0.0.14" }
serde = { version = "0.9", optional = true }

[dev-dependencies]
serde = "0.9"
serde_json = "0.9"
rustc-serialize = "0.3"
rmp-serde = "0.12"

[features]
benchmarks = []
default = ["serde"]
get-libsodium = ["libsodium-sys/get-libsodium"]
